version: '3.9'

services:

  node:
    build:
      context: ./node
      dockerfile: ./Dockerfile
    volumes:
      - ${HOST_SOURCE_CODE_DIR}:/var/www/current
      - ${WAIT_FOR_IT_PATH}:/usr/local/bin/wait-for-it.sh
    depends_on:
      - php-fpm
    networks:
      backend:
        aliases:
          - ${PHP_FPM_ALIAS}

  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: ./Dockerfile
      args:
        - PHP_FPM_VERSION=${PHP_FPM_VERSION}
    environment:
      - APP_SECRET_KEY
      - APP_CREATE_USERS_TOKEN
      - APP_SHOW_ERRORS
      - XDEBUG_MODE
    volumes:
      - ${HOST_SOURCE_CODE_DIR}:/var/www/current
      - ${PHP_FPM_ENV_PATH}:/usr/local/etc/php-fpm.d/env-var.conf
      - ${WAIT_FOR_IT_PATH}:/usr/local/bin/wait-for-it.sh
    networks:
      backend:
        aliases:
          - ${PHP_FPM_ALIAS}

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    volumes:
      - ${HOST_SOURCE_CODE_DIR}:/var/www/current
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available/
      - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d
      - ${WAIT_FOR_IT_PATH}:/usr/local/bin/wait-for-it.sh
    depends_on:
      - node
    command: [ "wait-for-it.sh", "${PHP_FPM_ALIAS}:9000", "-s", "-t", "240", "--", "nginx" ]
    ports:
      - "${NGINX_API_HOST_HTTP_PORT}:81"
      - "${NGINX_UI_HOST_HTTP_PORT}:80"
    networks:
      backend:
        aliases:
          - ${NGINX_ALIAS}

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
