version: '3.9'

services:
  php-fpm:
    build:
      context: ./php-fpm
      dockerfile: ./Dockerfile
      args:
        - PHP_FPM_VERSION=${PHP_FPM_VERSION}
    environment:
      - MYSQL_ALIAS
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_USER
      - APP_SECRET_KEY
      - APP_CREATE_USERS_TOKEN
      - APP_SHOW_ERRORS
      - APP_3RD_PARTY_PUBLICATIONS_API_KEY
    volumes:
      - ${HOST_SOURCE_CODE_DIR}:/var/www/current
      - ${PHP_FPM_ENV_PATH}:/usr/local/etc/php-fpm.d/env-var.conf
      - ${WAIT_FOR_IT_PATH}:/usr/local/bin/wait-for-it.sh
    depends_on:
      - mysql
    command: [ "wait-for-it.sh", "${MYSQL_ALIAS}:3306", "-s", "-t", "60", "--", "php-fpm" ]
    networks:
      backend:
        aliases:
          - ${PHP_FPM_ALIAS}

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    volumes:
      - ${HOST_SOURCE_CODE_DIR}:/var/www/current
      - ${NGINX_CONF_PATH}:/etc/nginx/nginx.conf
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available/
      - ${NGINX_CONFD_PATH}:/etc/nginx/conf.d
      - ${WAIT_FOR_IT_PATH}:/usr/local/bin/wait-for-it.sh
    depends_on:
      - php-fpm
    command: [ "wait-for-it.sh", "${PHP_FPM_ALIAS}:9000", "-s", "-t", "60", "--", "nginx" ]
    ports:
      - "${NGINX_API_HOST_HTTP_PORT}:81"
      - "${NGINX_UI_HOST_HTTP_PORT}:80"
    networks:
      backend:
        aliases:
          - ${NGINX_ALIAS}

  mysql:
    build:
      context: ./mysql
      dockerfile: ./Dockerfile
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
    volumes:
      - ${MYSQL_DATA_PATH}:/docker-entrypoint-initdb.d/
      - ${MYSQL_CNF_PATH}:/etc/mysql/conf.d/my.cnf
    ports:
      - "${MYSQL_PORT_HOST}:3306"
    networks:
      backend:
        aliases:
          - ${MYSQL_ALIAS}

networks:
  backend:
    driver: ${NETWORKS_DRIVER}
